/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddUsers: typeof import('./src/components/AddUsers.vue')['default']
    Button: typeof import('primevue/button')['default']
    ClockCard: typeof import('./src/components/presentational/ClockCard.vue')['default']
    ClockContainer: typeof import('./src/components/containers/ClockContainer.vue')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    FloatingConfigurator: typeof import('./src/components/FloatingConfigurator.vue')['default']
    GanttChart: typeof import('./src/components/GanttChart.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    ListProcess: typeof import('./src/components/ListProcess.vue')['default']
    ListUsers: typeof import('./src/components/ListUsers.vue')['default']
    Loader: typeof import('./src/components/Loader.vue')['default']
    LoaderGanttChartAction: typeof import('./src/components/LoaderGanttChartAction.vue')['default']
    Message: typeof import('primevue/message')['default']
    Overlay: typeof import('./src/components/Overlay.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaveLoader: typeof import('./src/components/SaveLoader.vue')['default']
    Select: typeof import('primevue/select')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    Timer: typeof import('./src/components/presentational/Timer.vue')['default']
    Toast: typeof import('primevue/toast')['default']
  }
}
